name: Merge to main branch
# Will be triggered on a merge to the main branch (via a PR). Does all verification steps as in pr-verification.yml and it everything passes then it will publish the resulting Docker image.
on:
  push:
    branches: [ "main" ]
jobs:
  prepare-tag:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
      - id: set-tag
        run: echo "image-tag=hivebox-py:latest" >> $GITHUB_OUTPUT
  merge-verify:
      needs: prepare-tag
      uses: ./.github/workflows/build-and-test.yml
      with:
        image_tag: ${{ needs.prepare-tag.outputs.image-tag }}
  publish-image:
    needs: [prepare-tag, merge-verify]
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: Load Docker image from tarball
        run: docker load -i image.tar
      - name: Publish Docker image
        run: echo "Publishing Docker image with tag ${{ needs.prepare-tag.outputs.image-tag }}
